### ISSUE TITLE
Idea: during contract deployment phase of starting, create a few tables with some of the hardhat wallets

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/local-tableland#106]
Had a chat with @awmuncy today and idea of some kind of automatic table creation mechanism at startup.  We currently lean on the healthbot table for a simple smoke screen type of test.  This isn't ideal because it's not a very interesting table and the schema and existence of the healthbot table are defined in the validator, and depending on that here is potentially fragile.

As a discussion starter I can think of a few different ways to accomplish this.
- automatically create a few tables and document their existence and schema, and the accounts that own them.
- create some examples, or a mechanism to add startup scripts that enable the developer to easily control this kind of thing on a per project basis.

**Comment by joewagner** [comment]
A thought here:
When the hardhat plugin is up and running, folks can probably use it to accomplish this kind of thing.

**Comment by dtbuchholz** [comment]
Somewhat related—I could imagine a starter flow where you pick your template sorta thing, which then creates the tables for you with a pre-made config file.

For example, `Gaming` as an option would produce a game state table, users table, etc. Or for `NFT (simple)`, it would create a main table and attributes tables...for `NFT (complex)`, it would replicate the Rigs table setup. Something along those lines!

**Comment by dtbuchholz** [comment]
(I guess this might be your second point in the original issue)

**Comment by joewagner** [comment]
This work is captured in the Table Configurations project.  I'm closing this as part of the Linear cleanup.
