### ISSUE TITLE
No Response from JSON RPC

### ISSUE THREAD

**Issue by Keerthana-Bidarakoppa** [tablelandnetwork/local-tableland#164]
Using curl commands to reach out to JSON RPC of local-validator node but not receiving any response:

`curl --location --request POST 'http://x.x.x.x:8080/rpc'  --header 'Content-Type: application/json'  --header 'Authorization: Bearer '"$SIWE_TOKEN"''  --data-raw '{
    "jsonrpc": "2.0",
     "method": "tableland_validateCreateTable",
     "params": [{
         "create_statement": "CREATE TABLE rpc_counter_6 (id int, name text)"     }]
 }' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying x.x.x.x:8080...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 8080 (#0)
> POST /rpc HTTP/1.1
> Host: x.x.x.x:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer eyJtZXNzYWdlIjoiVGFibGVsYW5kIHdhbnRzIHlvdSB0byBzaWduIGluIHdpdGggeW91ciBFdGhlcmV1bSBhY2NvdW50OlxuMHhmMzlGZDZlNTFhYWQ4OEY2RjRjZTZhQjg4MjcyNzljZmZGYjkyMjY2XG5cbk9mZmljaWFsIFRhYmxlbGFuZCBTREtcblxuVVJJOiBodHRwczovL3RhYmxlbGFuZC54eXpcblZlcnNpb246IDFcbkNoYWluIElEOiA4MDAwMVxuTm9uY2U6IFV4VTJ2cktHYXR6OEpCMzdGXG5Jc3N1ZWQgQXQ6IDIwMjMtMDEtMDRUMDk6NDY6MzEuMzkyWlxuRXhwaXJhdGlvbiBUaW1lOiAyMDIzLTAxLTA0VDE5OjQ2OjMxLjM5MloiLCJzaWduYXR1cmUiOiIweDhmNTg4NTUyMDE4NmMzMmU3YzhhOTVhOTlhYTkwYjNjNTg3ZThhNDRjNmY5MDFhN2E3Nzg2ZTQwMDM5MDEwYWE1MWE1MzM4NTljY2QzMGM3NzdjZmFkZDM4MDQ0MDEwNGVhY2NjODMyNDIxOGQzZDNlMTc0MzlkNzA0N2RmMzI2MWIifQ==
> Content-Length: 177
> 
* upload completely sent off: 177 out of 177 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept, Accept-Language, Content-Type, Authorization
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Trace-Id: 7c004e65-2c0a-45fd-8abe-e459151d7b8a
< X-Ratelimit-Limit: 10
< X-Ratelimit-Remaining: 9
< X-Ratelimit-Reset: Wed, 04 Jan 2023 10:10:29 UTC
< Date: Wed, 04 Jan 2023 10:10:29 GMT
< Content-Length: 0
< 
* Connection #0 to host x.x.x.x left intact
`
@joewagner any idea about issue resolution?
Can you also provide me a link to the slack channel?

**Comment by joewagner** [comment]
Hey @Keerthana-Bidarakoppa I can definitely try to help get things figured out. 
A few questions:
What commands are you using to start local-tableland?
What version of local-tableland, and node.js are you using?
Lastly, you have the url `http:x.x.x.x:8080/rpc` in your curl command.  Are those `x`s place holders, or is that the actual command you're running?  If they are placeholders what is the actual url you're using?

re: slack
We don't have a slack channel anymore.  You can find us on discord here: https://discord.gg/dc8EBEhGbg

**Comment by Keerthana-Bidarakoppa** [comment]
I use 
create a new empty directory and cd into it, 
`1. mkdir test-local && cd test-local
2. run npm install @tableland/local
3. run npx local-tableland`

Local Tableland version - 0.0.5- pre.2
Node.js version - v18.7.0

http:x.x.x.x:8080/rpc using x as placeholder for server IP-> http://<server IP>:8080/rpc. 

Thanks for the Discord link.

**Comment by joewagner** [comment]
@Keerthana-Bidarakoppa I have a couple more questions:
- When you start a local network, does the console output look like everything has started correctly? Or are there any error messages?  If things are running correctly you should see the message "Tableland is running!" followed by some ascii art of the tableland logo.
- Can you give the actual url you are using?  It should be either `http://localhost:8080`, or `http://127.0.0.1:8080`.  If it's not one of those that might be the root of problem you're seeing.  Can you try starting the network and then navigating to http://localhost:8080/query?s=select%20*%20from%20healthbot_31337_1 in a browser?

**Comment by Keerthana-Bidarakoppa** [comment]
- Yes, Console output shows everything has started locally and there are no error messages. I can see this - "Tableland is running!" followed by some ascii art of the tableland logo. I can also do SQL operations using tableland cli. But not getting response using JSON RPC.
- I am using http://localhost:8080. I navigated to the browser for the URL provided and see the below details

`[{"counter":1}]`
`Access-Control-Allow-Headers: Accept, Accept-Language, Content-Type, Authorization
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 15
Content-Type: application/json
Date: Mon, 16 Jan 2023 09:23:51 GMT
Trace-Id: cccc178a-a016-4ea0-aae8-d8c81cb09814
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 9
X-Ratelimit-Reset: Mon, 16 Jan 2023 09:23:52 UTC

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: localhost:8080
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
`

**Comment by joewagner** [comment]
@Keerthana-Bidarakoppa
In your issue description you say "No Response from JSON RPC".  Are you getting no response, or a status 200 response without any content in the body?
The RPC method you are calling might not be returning a body.  If status is less than 300 then it sounds like everything is working correctly.

**Comment by Keerthana-Bidarakoppa** [comment]
@joewagner I am receiving a response status 200 without any content in the body.
I am following the documentation here to run RPC curl commands https://docs.tableland.xyz/json-rpc-api.
I run create table query, the command returns 200 but I cannot see a table being created on local-tableland. 
Local-tableland list returns empty.

**Comment by joewagner** [comment]
@Keerthana-Bidarakoppa The example you provided has `"method": "tableland_validateCreateTable",`, which does not create a table.  `tableland_validateCreateTable` validates the create statement, so if it returns a 200 status that means the create statement is valid.

With all that said, Tableland is going to be depreciating the RPC endpoint at the end of this week.  If you are working on a new project its highly recommended the you build with the new API.
There are details here: https://dev.tableland.xyz/blog/launch-week-tableland-upgrades-more

**Comment by joewagner** [comment]
@Keerthana-Bidarakoppa Are you still having issues with this?

**Comment by Keerthana-Bidarakoppa** [comment]
@joewagner I followed the documentation for the validator API https://docs.tableland.xyz/validator-api. I can now receive response content with body.
However, I can only see examples of GET i.e to retrieve information from the already created tables. Does the API also provide support for POST i.e creating new tables?

**Comment by joewagner** [comment]
@Keerthana-Bidarakoppa This is a great question.  To answer this, it's best to first think about the way Tableland works. You can think of Tableland as having two main parts.
1. The Validator that provides the API and materializes data as tables.  [source](https://github.com/tablelandnetwork/go-tableland)
2. A registry contract that is deployed on each of the Tableland supported blockchains. [source](https://github.com/tablelandnetwork/evm-tableland)

With that in mind, the way you create a table is by submitting a transaction with a SQL create statement to the registry contract.  Within that transaction the create statement is emitted by the registry contract.  The Validators are listening to the events being emitted and they use the data in those events to create tables that can be read from.

Back to your question. No, there is not a validator api to create tables.  To create a table you will need to submit a transaction to the chain you want your table created on.

**Comment by Keerthana-Bidarakoppa** [comment]
@joewagner Thanks for the prompt response. I will take it from here. No more questions.
