### ISSUE TITLE
Cannot upgrade to newest SDK release

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/local-tableland#185]
As seen in this dependabot PR upgrading the SDK from 4.0.0-pre.1 to 4.0.0-pre.3 results in a typescript build error.
https://github.com/tablelandnetwork/local-tableland/pull/182

As best I can determine this is the result of the sdk's upgrade of `@tableland/evm` from v3.x to 4.0.0-pre.x.
When this upgrade was made `@tableland/evm` changed to publishing the typechain-types *.ts files.  This is the correct behavior, but a bug in TypeChain means that we have to stop checking for unused locals in order to build.
TypeChain bug is here: https://github.com/dethcrypto/TypeChain/issues/721

There is a fix for the issue here: https://github.com/dethcrypto/TypeChain/pull/776
The PR has been open for a while now.  In the mean time we can work around the problem by no longer strictly checking for unused locals.

**Comment by joewagner** [comment]
@dtbuchholz I can help with this, but just pinging you as a reminder to self.  Depending on how quickly TypeChain gets a fix for this, we might want to add something to the docs about using this workaround.

**Comment by dtbuchholz** [comment]
@joewagner gotcha, sounds good. So, we can monitor this being merged, and in `N` days from now, we go down the path of creating some docs? What sorta timeline are you thinking...maybe, check in 1 week from now, and if it's not merged, we create docs? Or maybe 2 weeks?

**Comment by dtbuchholz** [comment]
@joewagner following up here!

**Comment by joewagner** [comment]
@dtbuchholz Thanks for the reminder! I'd say let's avoid cluttering the docs unless a user opens an issue.  I have alerts on for the TypeChain issue and PR, when there's a fix I'll be sure to upgrade here.

**Comment by dtbuchholz** [comment]
(Thanks to Notion!) Cool, sgtm
