### ISSUE TITLE
Trouble running tests in debug mode

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/local-tableland#93]
**Describe the bug**
When using VSCode in debug mode or node with the --inspect flag the network is never finishing startup

**To Reproduce**

**Expected behavior**
Should be able to run tests in debug mode using VSCode or node --inspect

cc: @carsonfarmer

**Comment by joewagner** [comment]
With the latest version of this lib included in the [js-tableland](https://github.com/tablelandnetwork/js-tableland) tests, I can run tests with the --inspect-brk flag and inspect all the tests using the Chrome browser.

@carsonfarmer is there a specific vscode extension or adapter for typescript test debugging you like to use?

**Comment by carsonfarmer** [comment]
I've been using this one: https://marketplace.visualstudio.com/items?itemName=nilobarp.javascript-test-runner

**Comment by carsonfarmer** [comment]
But it is actually _using_ this https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug default, built-in debugger.

**Comment by joewagner** [comment]
Thanks! Looks like the registry deploy contract process is getting a debugger attached and it might not be letting the deploy process close normally.

**Comment by carsonfarmer** [comment]
I think that is correct, but I also isolated the problem to this `throw`: https://github.com/tablelandnetwork/local-tableland/blob/main/src/util.ts#L139. If I comment out that throw, the tests continue to run, and I can use breakpoints etc in the IDE. It appears that the debugger is actually logging its own information to stderr for some reason?

**Comment by joewagner** [comment]
Closed via #110
